### PR TITLE
#164694236 User should be able to see how long it takes to read an article

### PR DESCRIPTION
**Pull request by Rhytah**
#### What does this PR do?
* show reading time of an article

#### Description of tasks to be completed

- [x] add time estimator for reading an article

- [x] include `read_time` when displaying an article
#### How this can be manually tested
* Run application server using command `py manage.py runserver`
- using a broswer of your choice or `postman` application
   - enter endpoint to fetch article(s) `GET/ http://localhost:8000/api/articles/`

#### Any background context
* Readers would like to know an estimate of how long it would take them to read particular articles.
#### Relevant pivotal tracter stories
[#164694236](https://www.pivotaltracker.com/story/show/164694236)

### CODE REVIEW

**Review by frankopkusianwar — COMMENTED** [review]
@Rhytah why move the offset_query_param out of the class

**Comment by ghost** [comment]
can't the time frame be shown in this format: `1 min`, `5 mins`, `1 day`, `1 week`

**Comment by Rhytah** [comment]
> 
> 
> can't the time frame be shown in this format: `1 min ago`, `5 mins ago`, `1 day ago`, `1 week ago`

@ManuelDominic that would be out of the scope of the task. The user is meant to see how long it takes to read an article as opposed to when it was created.

**Comment by Rhytah** [comment]
> 
> 
> @Rhytah why move the offset_query_param out of the class

@frankopkusianwar I have refactored this back to previous state

**Review by sebbss — DISMISSED** [review]

**Review by kimbugp — APPROVED** [review]

**Pull request merged**
